hdx_inputs:
  dataset: "health-facility-counts-for-data-explorers"
  dataset_exceptions:
    NER: "hotosm_niger_health_facilities"
    MLI: "hotosm_mali_health_facilities"
    TCD: "hotosm_chad_health_facilities"
  boundaries: "unmap-international-boundaries-geojson"
